### ISSUE TITLE
Знайти фото танка

### ISSUE THREAD

**Issue by OliynykM** [OliynykM/PR4_OLIYNYK#2]
Знайти найкраще фото танка

**Comment by Khomanchuk** [comment]
ВИКОНУЮ

**Comment by Khomanchuk** [comment]
![image](https://user-images.githubusercontent.com/94034926/141082851-f270b678-6eba-4023-b437-329d287e6534.png)

**Comment by Khomanchuk** [comment]
Завдання виконав

**Comment by OliynykM** [comment]
Завершено

**Comment by Khomanchuk** [comment]
Так завершено
